import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import {SliderData} from '../components/SliderData.js'

export default function Home() {
  return (
    <div>

      <Head>
        <title>Swaranjali Jewels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Swaranjali Jewels" message="For precious moments to look at for ages..." />
      <Slider slides={SliderData} />
      <Instagram />
      
    </div>
  )
}
